//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tauron.Application.RadioStreamer.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RadioStreamerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RadioStreamerResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tauron.Application.RadioStreamer.Resources.RadioStreamerResources", typeof(RadioStreamerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add To Favorites ähnelt.
        /// </summary>
        public static string AddFavoritesLabel {
            get {
                return ResourceManager.GetString("AddFavoritesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finishing Update. ähnelt.
        /// </summary>
        public static string AfterCreationMessage {
            get {
                return ResourceManager.GetString("AfterCreationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An Error has Occured.\n The Error Code is: {0} ähnelt.
        /// </summary>
        public static string BassErrorMessage {
            get {
                return ResourceManager.GetString("BassErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bass Can&apos;t Initialized. The Error is: {0} ähnelt.
        /// </summary>
        public static string BassInitErrorMessage {
            get {
                return ResourceManager.GetString("BassInitErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prepating for Update. ähnelt.
        /// </summary>
        public static string BeforeCreationMessage {
            get {
                return ResourceManager.GetString("BeforeCreationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not Playing ähnelt.
        /// </summary>
        public static string BufferPercentageInvalid {
            get {
                return ResourceManager.GetString("BufferPercentageInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database is Upadating; ähnelt.
        /// </summary>
        public static string CreationProcessTitle {
            get {
                return ResourceManager.GetString("CreationProcessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Database File: {0} ähnelt.
        /// </summary>
        public static string DeleteDatabaseFilesMessage {
            get {
                return ResourceManager.GetString("DeleteDatabaseFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Elapsed Time:  ähnelt.
        /// </summary>
        public static string ElapsedTime {
            get {
                return ResourceManager.GetString("ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile: ähnelt.
        /// </summary>
        public static string EqualazerControlProfileLabel {
            get {
                return ResourceManager.GetString("EqualazerControlProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activate Equalizer ähnelt.
        /// </summary>
        public static string EqualizerActivate {
            get {
                return ResourceManager.GetString("EqualizerActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View Fovorites ähnelt.
        /// </summary>
        public static string FavoritesLabel {
            get {
                return ResourceManager.GetString("FavoritesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language:  ähnelt.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        public static string NewLabel {
            get {
                return ResourceManager.GetString("NewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current Radio: {0} ähnelt.
        /// </summary>
        public static string NextRadioMessage {
            get {
                return ResourceManager.GetString("NextRadioMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quality Manager: Number: {0}, All: {1} ähnelt.
        /// </summary>
        public static string QualityManager {
            get {
                return ResourceManager.GetString("QualityManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Land:    {0} ähnelt.
        /// </summary>
        public static string RadioItemCountryLabel {
            get {
                return ResourceManager.GetString("RadioItemCountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description: {0} ähnelt.
        /// </summary>
        public static string RadioItemDescriptionLabel {
            get {
                return ResourceManager.GetString("RadioItemDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Genre:  ähnelt.
        /// </summary>
        public static string RadioItemGenre {
            get {
                return ResourceManager.GetString("RadioItemGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Genres:         {0} ähnelt.
        /// </summary>
        public static string RadioItemGenreLabel {
            get {
                return ResourceManager.GetString("RadioItemGenreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Qualitys ähnelt.
        /// </summary>
        public static string RadioItemNotReady {
            get {
                return ResourceManager.GetString("RadioItemNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Radio Title:   {0} ähnelt.
        /// </summary>
        public static string RadioItemTilteLabel {
            get {
                return ResourceManager.GetString("RadioItemTilteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title:  ähnelt.
        /// </summary>
        public static string RadioItemTitle {
            get {
                return ResourceManager.GetString("RadioItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please Wait ähnelt.
        /// </summary>
        public static string RadioItemWaitLabel {
            get {
                return ResourceManager.GetString("RadioItemWaitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        public static string RadioPlayerEffectsOptionLabel {
            get {
                return ResourceManager.GetString("RadioPlayerEffectsOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initializing ähnelt.
        /// </summary>
        public static string RadioPlayerStadeInitializing {
            get {
                return ResourceManager.GetString("RadioPlayerStadeInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Playing:  ähnelt.
        /// </summary>
        public static string RadioPlayerStadePlaying {
            get {
                return ResourceManager.GetString("RadioPlayerStadePlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paused:  ähnelt.
        /// </summary>
        public static string RadioPlayerStadeStopped {
            get {
                return ResourceManager.GetString("RadioPlayerStadeStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Track: {0}  ähnelt.
        /// </summary>
        public static string RadioTitleCurrentTrack {
            get {
                return ResourceManager.GetString("RadioTitleCurrentTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is Recording ähnelt.
        /// </summary>
        public static string RadioTitleIsRecording {
            get {
                return ResourceManager.GetString("RadioTitleIsRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Record ähnelt.
        /// </summary>
        public static string RecordButtonLabel {
            get {
                return ResourceManager.GetString("RecordButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove From Favorites ähnelt.
        /// </summary>
        public static string RemoveFavoritesLabel {
            get {
                return ResourceManager.GetString("RemoveFavoritesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search:  ähnelt.
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unkown ähnelt.
        /// </summary>
        public static string UnkownString {
            get {
                return ResourceManager.GetString("UnkownString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Ready! ähnelt.
        /// </summary>
        public static string UpdateAvailableCaption {
            get {
                return ResourceManager.GetString("UpdateAvailableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An Update is Ready! Install? ähnelt.
        /// </summary>
        public static string UpdateAvailableMessage {
            get {
                return ResourceManager.GetString("UpdateAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Metadata ähnelt.
        /// </summary>
        public static string ViewMetadataLebel {
            get {
                return ResourceManager.GetString("ViewMetadataLebel", resourceCulture);
            }
        }
    }
}
